language: php

cache:
  apt: true
  directories:
    - $HOME/.composer/cache

env:
  global:
    - setup=basic
    - coverage=false
    - phpstan=false

before_install:
  - sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-fr

install:
  - if [[ $phpstan = 'true' ]]; then travis_retry composer require --dev phpstan/phpstan; fi
  - if [[ $setup = 'basic'  ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-stable; fi
  - |
    if [[ $setup = 'lowest' ]]; then
        composer require sebastian/comparator:"~1.2.4" --no-update --dev
        travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-stable --prefer-lowest
    fi

script:
  - composer phpunit
  - if [[ $phpstan = 'true' ]]; then composer phpstan; fi

matrix:
  include:
    - php: nightly
      env: setup=stable
